---
title: "Gov 50 Final Project"
author: "Kaitlyn Tran"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---



Project Research Question (Second Milestone):

How does immigration policy around noncitizens differ between U.S. presidential administrations? In this study, I will be observing data on noncitizen apprehension, noncitizen removal, and noncitizen returns from the U.S. to determine the immigration policy around noncitizens. My hypothesis would be that immigration policy around noncitizens is stricter over years when a Republican administration is in power than when a Democratic administration is in power. The rate of noncitizen apprehension, removal, and returns would be comparatively larger in a Republican administration than in a Democratic administration. My dataset is a Kaggle dataset on “US Immigration Statistics” from 1980 to 2021. My unit of analysis is a Presidential administration, and I will group the years based on each U.S. President that was in power. The explanatory variable of interest is whether the administration is Republican or Democrat (this is not within the dataset, so I would need to find the information independently). My outcome variables are the “number of noncitizens apprehended in the U.S.,” “number of noncitizens removed from the U.S.,” and “number of noncitizen returns from the U.S.” I grouped these variables as “immigration policy around noncitizens” in my research question. If I observe higher numbers of noncitizen apprehension/removal/return in most Republican administrations, my hypothesis would be supported. If I observe higher numbers of noncitizen apprehension/removal/return in a significant number of Democratic administrations, my hypothesis would not be supported.



Project Proposal (First Milestone):

I am interested in exploring data related to how politicians trend on social media (measured through hashtags or the frequency of their name in a post/tweet/etc) and how that correlates with their popularity ratings at the time.

Alternatively, I'm also thinking about looking at the frequency of migration news articles in the media and how the increase/decrease of media attention correlates with negative/positive public opinion on migration. A problem I see with this is that the public opinion on migration might not be surveyed frequently enough to be able to examine any connection with the increase/decrease of media articles. Potentially I could just conduct this at a broader scale and look at this yearly and see if, in a year with high media attention on migration, there was a significant increase/decrease in positive/negative public opinion. 


